### ISSUE TITLE
Can't login after installing blueprints

### ISSUE THREAD

**Issue by frshjb373** [litzinger/blueprints.eeaddon#1]
I installed this plugin on EE ver 2.9.3, ran into a bunch of errors, reverted to old version of Blueprints thinking it would resolve, however now I can't login to backend. Any help and/or advise is much appreciated. Thank you in advance!

**Comment by litzinger** [comment]
I don't support this extension anymore, which is why its on Github. If it works for you then great, if not I can't help. I stopped selling and supporting it because changes in EE made it difficult to support and actually broke a couple features. Please see https://boldminded.com/news/blueprints-is-no-longer-for-sale#continue

**Comment by frshjb373** [comment]
Yes, I read this article already, but was hoping for at least some sort of resource that may help resolve issue. We've scoured the web and cannot yet find a fix.

**Comment by frshjb373** [comment]
I'm fine with not using plugin, just need to revert back to be able to login now.

**Comment by frshjb373** [comment]
Too bad...it's a great product and we use on every site we have.
